---
#MySQL Settings
mysql_root_password: "mysqlpassword"
mysql_db: "wordpress"
mysql_wp_user: "wpuser"
mysql_wp_password: "wppassword"

#HTTP Settings
http_host: "brm.smn.com.ua"
http_conf: "your_domain.conf"
http_port: "80"
