---
# tasks file for config_mysql_masters
- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create MySQL user for Replication
  mysql_user:
    name: "{{ mysql_replica_user }}"
    password: "{{ mysql_replica_password }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    host: "{{ hostvars[item].ansible_default_ipv4.address }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ groups['db_slaves'] }}"
  tags: [ mysql ]


- name: Site config
  template:
    src: "my.cnf.j2"
    dest: "/etc/mysql/conf.d/mysql.cnf"
  notify: Restart MySQL

#- name: Dump WordPress DB
#  mysql_db:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    name: "{{ mysql_db }}"
#    single_transaction: yes
#    state: dump
#    target: /tmp/dump.sql

#- name: Get binlog file and position
#  mysql_replication:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    mode: getmaster
#  register: master

#- name: look for binlod file and position
#  debug:
#    msg: File- {{ master.File }} and Position- {{ master.Position }}

