---
- name: Install Prerequisites
  hosts: all
  become: yes
  roles:
  - update_system

- name: Install MySQL
  hosts: db_servers
  become: yes
  roles:
  - install_mysql

- name: Config DB_Servers
  hosts: db_servers
  become: yes
  roles:
  - config_mysql
  
- name: Config DB_Masters
  hosts: db_masters
  become: yes
  roles:
  - config_mysql_master

- name: Config DB_Slaves
  hosts: db_slaves
  become: yes
  roles:
  - config_mysql_slave

- name: Install Webserver
  hosts: webservers
  become: yes
  roles:
  - install_nginx
  - install_php
  - install_wordpress
  - config_nginx
  - config_wordpress
  - config_ssl

