---
# tasks file for install_wordpress
- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/html"
    remote_src: yes
    creates: "/var/www/html/wordpress"
  tags: [ wordpress ]

- name: Set ownership
  file:
    path: "/var/www/html"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ wordpress ]

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/html/wordpress/ -type d -not -perm 0750 -print >&1 -exec chmod 750 {} \\;"
  changed_when: False
  tags: [ wordpress ]

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/html/wordpress/ -type f -not -perm 0640 -print >&1 -exec chmod 640 {} \\;"
  changed_when: False
  tags: [ wordpress ]
