---
# tasks file for config_mysql
- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [ mysql, mysql-root ]

#    - name: Remove all anonymous user accounts
#      mysql_user:
#        name: ''
#        host_all: yes
#        state: absent
#        login_user: root
#        login_password: "{{ mysql_root_password }}"
#      tags: [ mysql ]
#
#    - name: Remove the MySQL test database
#      mysql_db:
#        name: test
#        state: absent
#        login_user: root
#        login_password: "{{ mysql_root_password }}"
#      tags: [ mysql ]
#
- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: mysql_config_status
  tags: [ mysql ]
  